# Generated by Django 4.2.5 on 2023-09-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformacoesGerais',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('variavel', models.CharField(blank=True, max_length=255, null=True)),
                ('unidade', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'informacoes_gerais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerieDetalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade_id', models.IntegerField(blank=True, null=True)),
                ('localidade_nivel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('localidade_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('serie_ano', models.IntegerField(blank=True, null=True)),
                ('serie_valor', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'serie_detalhes',
                'managed': False,
            },
        ),
    ]
